### ISSUE TITLE
Ability to select a field for header/footer inclusion

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1511]
- idea is to set, in Control Settings, whether the field is shown in the header/footer (could also be left/center/right (margin boxes))
- constraints
  - one field can be assigned to 0-1 margin boxes
  - only margin box can only contain one field (probably)
- XSLT should copy field to output, when in PDF mode, w/ class, because CSS moves the elements

Example of LESS to move an output field to the footer:

``` css
@media print {
  .orbeon .my-ssn-output {
    position: running(footer-field);
  }
  .orbeon .my-ssn-output .xforms-label {
    display: inline;
  }
  .orbeon .my-ssn-output .xforms-label:after {
    content: ": ";
  }
}
@page {
  @bottom-left {
    content: element(footer-field);
  }
}
```
