### ISSUE TITLE
Easy way to enable hints in PDF

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1811]
Here is CSS which works:

``` css
@media print {
    .orbeon #xforms-form .xforms-hint { display: block; clear: none }
}
```

We had at least 2 users asking us how to do this.

[+1 from customer](https://basecamp.com/1721271/projects/5858694/messages/26279827)
