### ISSUE TITLE
PDF: Extra space under empty Fields Date if hints are shown

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2347]
See screenshot. Only happens if the date is empty. Doesn't happen with regular date field.

Add the following CSS to show the hints:

```css
.orbeon #xforms-form .xforms-hint {
    display: block;
}
```

![bad](https://cloud.githubusercontent.com/assets/105769/9395475/9a7b9d6c-4743-11e5-8347-288607d64872.png)
