### ISSUE TITLE
Yes/No Answer, Single Checkbox and Boolean Input look funny on iOS

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2710]
See screenshot. They look different from the other checkboxes and radio buttons.

![2016-04-12 10 27 16](https://cloud.githubusercontent.com/assets/105769/14470695/d33c4820-009f-11e6-93b0-1b1aa42c67f7.png)

**Comment by ebruchez** [comment]
Culprit is this in `form-runner-base.less`:

```css
    // But for boolean inputs, no background and border (for IE)
    .xforms-type-boolean input { background: none; border: none }
````

This is meant only for IE, and only for Boolean inputs.
