### ISSUE TITLE
Bad fr:us-phone layout with form-level label placeholders

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3227]
See screenshot.

![screen shot 2017-06-02 at 10 48 03 am](https://cloud.githubusercontent.com/assets/105769/26738482/20f85466-4783-11e7-9dff-81324ef73103.png)

**Comment by ebruchez** [comment]
That's because `fr:us-phone` includes internally:

```xml
<xf:hint appearance="minimal">(555) 555-5555</xf:hint>
```

And this CSS rule applies:

```css
.orbeon .xforms-hint-appearance-full .xforms-hint {
    display: block;
    width: 100%;
    clear: both;
}
```
