### ISSUE TITLE
CSS id rewriter doesn't work in media queries

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3251]
This for example doesn't work:

```css
@media (max-width: 980px) {
  .orbeon-portlet-div #xforms-form .row {
    margin-left: 0;
    margin-right: 0;
  }
  .orbeon-portlet-div #xforms-form .row .span12 {
    margin-left: 0;
    margin-right: 0;
  }
}
```

That's because `rewriteCSS()` matches the outer selector and block but then doesn't identify the nested selector and block.

Needed for #2843.

**Comment by ebruchez** [comment]
The reason we want an id is that Liferay uses an id. We could hack around by producing:

```css
@media (max-width: 980px) {
  #content .orbeon-portlet-div .row {
    margin-left: 0;
    margin-right: 0;
  }
  #content .orbeon-portlet-div .row .span12 {
    margin-left: 0;
    margin-right: 0;
  }
}
```

as `#content` is a Liferay id which must not be rewritten.
