### ISSUE TITLE
FB: Grid with rowspan="1" doesn't take height

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3283]
We have this:

```css
.orbeon .fr-view .xbl-fr-grid .fr-grid.fr-editable .fr-grid-tr {
    height: 60px;
}
```

But when there is a `<tr>`, this rule takes over:

```css
.orbeon .xbl-fr-grid .fr-grid:not(.fr-repeat) .fr-grid-body tr:last-of-type {
    height: auto;
}
```

Semi-regression: with 2016.3, there is some height, but not the full height.

Also, there should not be a `rowspan="1"`.
