### ISSUE TITLE
CSS: don't use -10000px trick

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3621]
We have this CSS in xforms.js:

```css
.xforms-disabled,
.xforms-case-deselected,
.xforms-case-deselected .xforms-case-selected {
    top: -10000px; // this so that no space is visible on the page
    left: -10000px; // this so that no space is visible on the page
    position: absolute;
}
```

This was probably done so that JavaScript components like the Rich Text Editor could initialize even when hidden or in a case. But that's not what we need to do anymore. In particular with #1117 some markup in is not even present in the page anymore.

In addition, this causes problems. For example a disabled control with `tabindex="0"` can still be focused when positioned off-screen, which is of course not what we want.
