### ISSUE TITLE
Option to disable background on calculated fields with labels

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4004]
Following #3804, we'd like the ability to disable this for some fields. I suggest we could have an `appearance="minimal"`.

See also #3583.

**Comment by ebruchez** [comment]
See also  #3821 which introduces `.xforms-field` on the nested `<output>`.

**Comment by ebruchez** [comment]
And since 2018.2 we also have an `appearance="xxf:multiline"` which enables word wrap with:

```less
.xforms-output.xforms-output-appearance-xxforms-multiline {
    output[role = textbox] {
        white-space: normal;
        word-wrap: break-word; // called `overflow-wrap` as of 2013 (http://www.w3.org/TR/css3-text/#overflow-wrap-property)
        min-height: @controlsHeight;
        height: auto;
    }
}
```

Incidentally, I am not sure in which case we wouldn't want multiline then the content becomes wider, actually. Either that or try to do what readonly input fields do, which is having scrolling when you select. But I don't think it's possible to emulate that scrolling with just a `<span>`. So let's consider supporting multiline in all cases.

We show "fields" in the following cases:

- `<xf:output>` with label in `edit` modes
- many controls in `view` modes, including `<xf:input>`, etc.

We'd like to add:

- except for `<xf:output appearance="minimal">`
