### ISSUE TITLE
Rich text: ability to preserve colors in PDF

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4158]
The issue right now is that our version of Bootstrap has:

```css
@media print {
  * {
    text-shadow: none !important;
    color: #000 !important; // Black prints faster: h5bp.com/s
    background: transparent !important;
    box-shadow: none !important;
  }
```

Bootstrap 4 doesn't have this AFAICT.

This makes all printed text in black with a transparent background.

This makes some sense: gray colors and lines don't print as well on black and white, and so generally should be adjusted to be just black and white. However, it's not always the correct decision.

We'd like an option, at least, to say: "make everything black and white except what's within rich text", knowing that the elements can be almost arbitrarily nested. In XPath, you would write `//*[empty(ancestor::*[...is-rich-text-element...])]`. CSS doesn't have such a construct yet. The way this is done usually is to apply the rule to all, but then have a stronger rule that sets what happens within specific subtrees.

To pick just one color, a workaround would be this:

```css
@media print {
  .orbeon .xbl-fr-explanation *[style *= 'color: #ff0000'] {
    color: red !important;
  }
}
```

But it doesn't scale to all colors. This said, we could catch the specific default colors of the TinyMCE color chooser:

<img width="186" alt="Screen Shot 2019-08-16 at 11 29 34 AM" src="https://user-images.githubusercontent.com/105769/63189594-322c7300-c019-11e9-9662-7d3f87dc4b10.png">

This would work when only using `textcolor` but not the [HSV `colorpicker`](https://www.tiny.cloud/docs-4x/plugins/colorpicker/).

With `!important`, I don't think we can do it, as that overrides even the `style` attribute which TinyMCE uses for specifying colors (which is not great, by the way), and we cannot create a stronger rule with `!important` which says to use the `style` attribute, after all. So we could remove the `!important`, as a first step. But this allows things like titles, headings, etc. to keep their colors and backgrounds.

- Remove `!important` from the default rules.
- Create new rules that apply only to the elements we'd like to disable.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966559/messages/1995641472) and [+1 from customer](http://discuss.orbeon.com/Text-color-styling-in-rich-text-editor-not-applying-in-PDF-td4663510.html)

See also #1670.
