### ISSUE TITLE
Make bottom form buttons and status sticky

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4809]
This might even be a good default. Add something like this:

```css
.orbeon .fr-buttons {
    position: fixed;
    bottom: 0;
    left: 0;
    padding: 10px;
    margin-top: 10px;
    background-color: #eeeeee;
    border-top: 2px solid #ccc;
}
```

Colors and sizes to be adjusted.

This shouldn't kick in when embedded, or only optionally. For example within Liferay it doesn't make sense probably, but in embedded offline it might.
