### ISSUE TITLE
Don't show placeholders for readonly fields 

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5372]
The following CSS does it for the date and phone number fields, and this RFE calls for this CSS to there out-of-the-box, and also done for all the other fields for which we have placeholders.

```css
.xbl-fr-date.xforms-readonly      input::placeholder { visibility: hidden }
.xbl-fr-us-phone .xforms-readonly input::placeholder { visibility: hidden }
```

[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/5078225776)

**Comment by ebruchez** [comment]
Maybe something like this could work in a general way:

```css
input:read-only::placeholder, textarea:read-only::placeholder {
  visibility: hidden;
}
```
