### ISSUE TITLE
Improvements to PDF header/footer configuration

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5776]
Following #5576:

1. ability to include the value of a form controls specified by CSS class name
2. ability to add custom CSS rules for header/footer styling

For point 1, here is how it was done before:

```css
.my-control-header-class {
    position: running(my-custom-name);
  }

@page {
    @top-left {
        content: element(my-custom-name);
    }
}
```

For point 2, we now output inline `@page` directives in `print-pdf-notemplate.xsl`, and it doesn't seem like the PDF processor is able to combine those directives with other CSS directives. If so, this means we'll need to add a special way to provide custom CSS for header/footer.
