### ISSUE TITLE
Don't let buttons overflow grids

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5851]
```css
.orbeon .xbl-fr-grid .fr-grid .xforms-trigger-appearance-full button {
    max-width: 100%;
    word-wrap: break-word;
    white-space: break-spaces;
}
```
