### ISSUE TITLE
Attachment control not visible on iOS

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6420]
I can remove existing attachments, but we hide the drag and drop area on iOS.

This probably regressed with #5814.

[+1 from customer](https://3.basecamp.com/3600924/buckets/24212679/messages/7636216707)

**Comment by ebruchez** [comment]
In `attachment.less`:

```less
    &.xforms-ios, .xforms-ios & {
        // As of 2020-05-29, drag and drop does not work on iOS, even on an iPad with multitasking.
        // So we hide the drop area.
        .fr-attachment-drop {
            display: none;
        }
    }
```

An easy fix would be to not hide the drop area, which would show the selection link.
