### ISSUE TITLE
Empty Formatted Text Area in view mode shows lighter gray line

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6692]
<img width="973" alt="image" src="https://github.com/user-attachments/assets/6eacf6f6-69b2-4c52-ba51-ce44c524cf3a" />

**Comment by ebruchez** [comment]
Possible regression.

**Comment by ebruchez** [comment]
Only for Formatted Text Area. Due to:

```css
.orbeon .fr-mode-view .xbl-fr-tinymce .xforms-output.xforms-mediatype-text-html > .xforms-output-output {
    overflow-x: scroll;
 }
```
