### ISSUE TITLE
PDF header/footer lines cannot be removed with CSS

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6851]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/8424905258)

**Comment by ebruchez** [comment]
Possibly changed with #6460.

**Comment by ebruchez** [comment]
Issue: if I override the CSS with custom external CSS as follows, the headers and footers disappear:

```css
@page {
    border-top: none !important;
    border-bottom: none !important;
}

@page {
    @top-left {
        border-bottom: none !important;
    }
    @top-center {
        border-bottom: none !important;
    }
    @top-right {
        border-bottom: none !important;
    }
    @bottom-left {
        border-top: none !important;
    }
    @bottom-center {
        border-top: none !important;
    }
    @bottom-right {
        border-top: none !important;
    }
}
```
